---
- name: Play-1....
  hosts: ubuntu
  become: true
  tasks:
    - name: Install git on ubuntu
      ansible.builtin.apt:
        name: git
        state: present


- name: Play-2....
  hosts: fedora
  become: true
  tasks:
    - name: Install git on fedora
      ansible.builtin.yum:
        name: git
        state: present
