---
- name: "Playbook: configure from text file"
  gather_facts: false
  hosts: cisco 

  tasks:
    - name: "T1: configure device from text file"
      ios_config:
        src: /root/router/config1.txt
      register: output
      
    - debug: var=output.stdout_lines