---
- name: IOS Command to save running config
  gather_facts: false
  hosts: network
  tasks:
    - name: show run
      ios_command:
        commands: show run
      register: show_run_output

    - name: save show run into text file
      copy:
        content={{ show_run_output.stdout_lines | to_nice_yaml }}
        dest=./documentation/network/{{ inventory_hostname }}_run_config.txt
