---
- name: "Playbook: Configure interfaces" 
  gather_facts: false
  hosts: CORE01
  tasks:

    - name: configure interface
      ios_interface:
        name: "{{ item }}"
        speed: '100'
        duplex: full

      register: commands
        
      with_items:

        - 'GigabitEthernet0/0'
        - 'GigabitEthernet0/1'

    -  debug: 
        var: commands
