---

- name: config hostname and save config 
  gather_facts: false
  hosts: all
  tasks:

    - name: config hostname 
      ios_config:
        lines:
          - hostname "{{ inventory_hostname }}"
      notify: "save config"
      
  handlers:
    - name: save config
      ios_command:
        commands: "write mem"
        timeout: 20
      when: not ansible_check_mode   
   
