---
- name: Playbook-01-Gather Facts
  hosts: distribution 
  tasks:
    - name: ios facts on distribution
      ios_facts:
      register: output

    - name: copy ios facts to file 
      copy:
        content: "{{ output | to_nice_json }}"
        dest: "./documentation/distribution/{{ inventory_hostname }}_IOS_FACTS.json"
