---
- name: "Play: save config and take backup"
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy run config to startup
      cisco.ios.ios_command:
        commands: wr

    - name: Show run
      cisco.ios.ios_command:
        commands: show run
      register: config

    - name: Save output to backup folder
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "configuration/show_run_{{ inventory_hostname.lower() }}.ios"
        mode: '0644'
