# test ping from ansible to all node
---
- name: "PLAYBOOK: PING"
  hosts: all
  become: true
  tasks:

    - name: Ping to all node
      ansible.builtin.ping:
      register: output

    - name: Debug ping
      ansible.builtin.debug:
        msg: "{{ output.ping }}"
