# use of debug module
---
- name: Print Variable
  hosts: all
  vars:
    my_var: some thing
  tasks:
    - name: Print on terminal
      ansible.builtin.command: echo "I want to print {{ my_var }} on screen"
      register: result
      changed_when: false

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines }}"
