---
- name: Play-1....
  hosts: ubuntu
  become: true
  tasks:
    - name: Uninstall git on ubuntu
      ansible.builtin.apt:
        name: git
        state: absent


- name: Play-2....
  hosts: fedora
  become: true
  tasks:
    - name: Uninstall git on fedora
      ansible.builtin.yum:
        name: git
        state: absent
