---
- name: Play-1 install git
  hosts: all
  become: true
  tasks:
    - name: Update on ubuntu
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install git on ubuntu
      ansible.builtin.apt:
        name: git
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update on Fedora
      ansible.builtin.yum:
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Install git on Fedora
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_distribution == "Fedora"
